// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9N7UZGcsYVNsU0UH-wu56zYZTnpj9854',
    appId: '1:642612885440:web:9b1de12e8ef774c5803a25',
    messagingSenderId: '642612885440',
    projectId: 'ecoeats-6a9eb',
    authDomain: 'ecoeats-6a9eb.firebaseapp.com',
    storageBucket: 'ecoeats-6a9eb.appspot.com',
    measurementId: 'G-CQZYMMR12X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANYK3d63UbOb5iX5mqivAnkL7j8OTh7Ho',
    appId: '1:642612885440:android:6a64cce674e03f45803a25',
    messagingSenderId: '642612885440',
    projectId: 'ecoeats-6a9eb',
    storageBucket: 'ecoeats-6a9eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9VvBSvltpNsMwyWeVAzOjjx7lZuNNFg4',
    appId: '1:642612885440:ios:1b39d312463518ac803a25',
    messagingSenderId: '642612885440',
    projectId: 'ecoeats-6a9eb',
    storageBucket: 'ecoeats-6a9eb.appspot.com',
    iosBundleId: 'com.example.ecoeats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9VvBSvltpNsMwyWeVAzOjjx7lZuNNFg4',
    appId: '1:642612885440:ios:d2548f840868cb37803a25',
    messagingSenderId: '642612885440',
    projectId: 'ecoeats-6a9eb',
    storageBucket: 'ecoeats-6a9eb.appspot.com',
    iosBundleId: 'com.example.ecoeats.RunnerTests',
  );
}
